// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using NorthWind2023App.Models;

namespace NorthWind2023Library.Models;

public partial class ContactType
{
    public int ContactTypeIdentifier { get; set; }

    public string ContactTitle { get; set; }

    public virtual ICollection<Contacts> Contacts { get; set; } = new List<Contacts>();

    public virtual ICollection<Customers> Customers { get; set; } = new List<Customers>();

    public virtual ICollection<Employees> Employees { get; set; } = new List<Employees>();
}