// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using NorthWind2023App.Models;

namespace NorthWind2023Library.Models;

public partial class Orders
{
    public int OrderID { get; set; }

    public int? CustomerIdentifier { get; set; }

    public int? EmployeeID { get; set; }

    public DateOnly OrderDate { get; set; }

    public DateOnly RequiredDate { get; set; }

    public DateOnly ShippedDate { get; set; }

    public DateOnly DeliveredDate { get; set; }

    public int? ShipVia { get; set; }

    public decimal? Freight { get; set; }

    public string ShipAddress { get; set; }

    public string ShipCity { get; set; }

    public string ShipRegion { get; set; }

    public string ShipPostalCode { get; set; }

    public string ShipCountry { get; set; }

    public virtual Customers CustomerIdentifierNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual Shippers ShipViaNavigation { get; set; }
}