// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using NorthWind2023App.Models;

namespace NorthWind2023Library.Models;

public partial class Region
{
    public int RegionID { get; set; }

    public string RegionDescription { get; set; }

    public virtual ICollection<Territories> Territories { get; set; } = new List<Territories>();
}