// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace BogusProperGenderEntityApp.Models;

public partial class BirthDays
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    /// <summary>
    /// Person gender
    /// </summary>
    public Gender Gender { get; set; }

    public DateOnly? BirthDate { get; set; }

    public int? YearsOld { get; set; }

    public string Email { get; set; }
    
    public BirthDays(int id)
    {
        Id = id;
    }
}