// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWind2023App.Data;
using NorthWind2023App.Models;
using System;
using System.Collections.Generic;

namespace NorthWind2023App.Data.Configurations
{
    public partial class RegionConfiguration : IEntityTypeConfiguration<Models.Region>
    {
        public void Configure(EntityTypeBuilder<Models.Region> entity)
        {
            entity.HasKey(e => e.RegionID).IsClustered(false);

            entity.Property(e => e.RegionID).ValueGeneratedNever();
            entity.Property(e => e.RegionDescription)
            .IsRequired()
            .HasMaxLength(50)
            .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Models.Region> entity);
    }
}
