// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CustomIConfigurationSourceSample.Models;

/// <summary>
/// Represents a configuration setting entity with properties for storing key-value pairs.
/// </summary>
public partial class ConfigurationSetting
{
    public int Id { get; set; }

    public string Key { get; set; }

    public string Value { get; set; }
    public override string ToString() => $"{Key}:{Value}";

}