// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CalendarSqlQuerySample.Classes;
using CalendarSqlQuerySample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Calendar = CalendarSqlQuerySample.Models.Calendar;

namespace CalendarSqlQuerySample.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Calendar> Calendar { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(DataConnections.Instance.MainConnection).EnableSensitiveDataLogging()
            .LogTo(new DbContextToFileLogger().Log, new[]
                {
                    DbLoggerCategory.Database.Command.Name
                },
                LogLevel.Information);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Calendar>(entity =>
        {
            entity.HasKey(e => e.CalendarDate);

            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DayOfWeekName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.HolidayComputed)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasComputedColumnSql("(case when [Holiday]=(1) then 'Yes' else 'No' end)", false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}