// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWind2023Library.Models;

namespace NorthWind2023Library.Data.Configurations
{
    public partial class CategoriesConfiguration : IEntityTypeConfiguration<Categories>
    {
        public void Configure(EntityTypeBuilder<Categories> entity)
        {
            entity.HasKey(e => e.CategoryID);

            entity.Property(e => e.CategoryID).HasComment("Primary key");
            entity.Property(e => e.CategoryName)
            .IsRequired()
            .HasMaxLength(15)
            .HasComment("Name of a category");
            entity.Property(e => e.Description)
            .HasComment("Description of category")
            .HasColumnType("ntext");
            entity.Property(e => e.Picture)
            .HasComment("Image which represents a category")
            .HasColumnType("image");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Categories> entity);
    }
}
