// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWind2023Library.Models;

namespace NorthWind2023Library.Data.Configurations;

public partial class OrdersConfiguration : IEntityTypeConfiguration<Orders>
{
    public void Configure(EntityTypeBuilder<Orders> entity)
    {
        entity.HasKey(e => e.OrderID);

        entity.HasIndex(e => e.CustomerIdentifier, "IX_Orders_CustomerIdentifier");

        entity.HasIndex(e => e.EmployeeID, "IX_Orders_EmployeeID");

        entity.HasIndex(e => e.ShipVia, "IX_Orders_ShipVia");

        entity.Property(e => e.Freight).HasColumnType("money");
        entity.Property(e => e.ShipAddress).HasMaxLength(60);
        entity.Property(e => e.ShipCity).HasMaxLength(15);
        entity.Property(e => e.ShipCountry).HasMaxLength(15);
        entity.Property(e => e.ShipPostalCode).HasMaxLength(10);
        entity.Property(e => e.ShipRegion).HasMaxLength(15);

        entity.HasOne(d => d.CustomerIdentifierNavigation).WithMany(p => p.Orders)
            .HasForeignKey(d => d.CustomerIdentifier)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_Orders_Customers2");

        entity.HasOne(d => d.Employee).WithMany(p => p.Orders)
            .HasForeignKey(d => d.EmployeeID)
            .HasConstraintName("FK_Orders_Employees");

        entity.HasOne(d => d.ShipViaNavigation).WithMany(p => p.Orders)
            .HasForeignKey(d => d.ShipVia)
            .HasConstraintName("FK_Orders_Shippers");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Orders> entity);
}