// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWind2023Library.Models;

namespace NorthWind2023Library.Data.Configurations;

public partial class OrderDetailsConfiguration : IEntityTypeConfiguration<OrderDetails>
{
    public void Configure(EntityTypeBuilder<OrderDetails> entity)
    {
        entity.HasKey(e => new { e.OrderID, e.ProductID }).HasName("PK_Order_Details");

        entity.HasIndex(e => e.ProductID, "IX_OrderDetails_ProductID");

        entity.Property(e => e.UnitPrice).HasColumnType("money");

        entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
            .HasForeignKey(d => d.OrderID)
            .HasConstraintName("FK_Order_Details_Orders");

        entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
            .HasForeignKey(d => d.ProductID)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_Order_Details_Products");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<OrderDetails> entity);
}