// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using BogusProperGenderEntityApp.Classes;
using BogusProperGenderEntityApp.Models;
using EntityCoreFileLogger;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace BogusProperGenderEntityApp.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<BirthDays> BirthDays { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        /*
         * Get connection string from appsetting.json
         * Setup logging to a file under the app folder (see the project file for folder creation)
         */
        optionsBuilder.UseSqlServer(DataConnections.Instance.MainConnection)
            .EnableSensitiveDataLogging()
            .LogTo(new DbContextToFileLogger().Log, new[]
                {
                    DbLoggerCategory.Database.Command.Name
                },
                LogLevel.Information);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BirthDays>(entity =>
        {
            // setup enum conversion
            entity.Property(e => e.Gender)
                .HasConversion<int>()
                .IsRequired();

            // setup computed column
            entity.Property(e => e.YearsOld)
                .HasComputedColumnSql("((CONVERT([int],format(getdate(),'yyyyMMdd'))-CONVERT([int],format([BirthDate],'yyyyMMdd')))/(10000))", false);
        });

        /*
         * Only push mocked data while runing in Visual Studio IDE
         */
        if (EntitySettings.Instance.CreateNew)
        {
            modelBuilder.Entity<GenderData>().HasData(BogusOperations.GenderTypes());
            modelBuilder.Entity<BirthDays>().HasData(new List<BirthDays>(BogusOperations.PeopleList(20,338)));
        }


    }

}