// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BogusProperGenderEntityApp.Classes;
using BogusProperGenderEntityApp.Models;
using Microsoft.EntityFrameworkCore;

namespace BogusProperGenderEntityApp.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<BirthDays> BirthDays { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(DataConnections.Instance.MainConnection);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BirthDays>(entity =>
        {
            entity.Property(e => e.Gender)
                .HasConversion<int>()
                .IsRequired();

            entity.Property(e => e.YearsOld)
                .HasComputedColumnSql("((CONVERT([int],format(getdate(),'yyyyMMdd'))-CONVERT([int],format([BirthDate],'yyyyMMdd')))/(10000))", false);
        });

        modelBuilder.Entity<GenderData>().HasData(BogusOperations.GenderTypes());
        modelBuilder.Entity<BirthDays>().HasData(new List<BirthDays>(BogusOperations.CustomersList(20)));

    }

}