// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NameOfSpecialSample.Models
{
    public partial class usp_CustomersOrderByResult
    {
        public int CustomerIdentifier { get; set; }
        public string CompanyName { get; set; }
    }
}
