// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NameOfSpecialSample.Models
{
    public partial class usp_CustomersByCountryResult
    {
        public int CustomerIdentifier { get; set; }
        public string CompanyName { get; set; }
        public int? ContactId { get; set; }
        public string FullName { get; set; }
        public int? CountryIdentifier { get; set; }
        public string Phone { get; set; }
        public int? ContactTypeIdentifier { get; set; }
        public string Name { get; set; }
    }
}
