// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using KarenConsoleApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KarenConsoleApplication.Data.Configurations
{
    public partial class ContactTypeConfiguration : IEntityTypeConfiguration<ContactType>
    {
        public void Configure(EntityTypeBuilder<ContactType> entity)
        {
            entity.HasKey(e => e.Identifier);

            entity.Property(e => e.ContactType1)
                .HasMaxLength(50)
                .HasColumnName("ContactType");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactType> entity);
    }
}
