// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using KarenConsoleApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace KarenConsoleApplication.Data.Configurations
{
    public partial class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> entity)
        {
            entity.HasKey(e => e.Identifier).HasName("Customer$PrimaryKey");

            entity.ToTable("Customer");

            entity.Property(e => e.CompanyName).HasMaxLength(255);
            entity.Property(e => e.ContactName).HasMaxLength(255);

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.ContactTypeIdentifier)
                .HasConstraintName("FK_Customer_ContactTypes");

            entity.HasOne(d => d.GenderIdentifierNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.GenderIdentifier)
                .HasConstraintName("FK_Customer_Genders");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Customer> entity);
    }
}
