// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FormattableStringsSamplesApp.Models
{
    public partial class usp_HolidaysForMonthYearResult
    {
        public DateOnly CalendarDate { get; set; }
        public int CalendarYear { get; set; }
        public int CalendarDay { get; set; }
        public string DayOfWeekName { get; set; }
        public string Weekend { get; set; }
        public string Weekday { get; set; }
        public string Description { get; set; }
    }
}
