// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using M = FormattableStringsSamplesApp.Models; // conflict resolution
using Microsoft.EntityFrameworkCore;
using static ConfigurationLibrary.Classes.ConfigurationHelper;
namespace FormattableStringsSamplesApp.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<M.Calendar> Calendar { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(ConnectionString());

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<M.Calendar>(entity =>
        {
            entity.HasKey(e => e.CalendarDate);

            entity.Property(e => e.CalendarDateDescription)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DayOfWeekName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}