// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FormattableStringsSamplesApp.Models;

namespace FormattableStringsSamplesApp.Data
{
    public partial interface IContextProcedures
    {
        Task<List<usp_HolidaysForMonthYearResult>> usp_HolidaysForMonthYearAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
