// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Calendar = CalendarSqlQuerySample.Models.Calendar;

namespace CalendarSqlQuerySample.Data.Configurations
{
    public partial class CalendarConfiguration : IEntityTypeConfiguration<Calendar>
    {
        public void Configure(EntityTypeBuilder<Calendar> entity)
        {
            entity.HasKey(e => e.CalendarDate);

            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.DayOfWeekName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.HolidayComputed)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasComputedColumnSql("(case when [Holiday]=(1) then 'Yes' else 'No' end)", false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Calendar> entity);
    }
}
