// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.Collections.Generic;

namespace KarenConsoleApplication.Models;

public partial class ContactType
{
    public int Identifier { get; set; }

    public string ContactType1 { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}