// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System.Collections.Generic;

namespace KarenConsoleApplication.Models;

public partial class Gender
{
    public int id { get; set; }

    public string GenderType { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}