// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace KarenConsoleApplication.Models;

public partial class NewAccountTable
{
    public int Id { get; set; }

    public string CustomerAccountNumber { get; set; }
}